### ISSUE TITLE
multiselect menu underlaps footer

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#108]
See screenshot.

![google chrome001](https://cloud.githubusercontent.com/assets/102112/14950202/ce0da406-1004-11e6-8ce2-0492b9cc3ed5.jpg)

To repeat:

1. Visit the URL https://trypyramid.com/resources-extending-pyramid.html
2. From the filter packages select menu, select "Support: Unsupported".
3. While the select menu is open, the number of packages displayed will be four, and the menu will extend beneath the footer and become obscured.

Ideally the select menu would push down the content. I've tried fiddling around with various CSS properties, but could not come up with the magic combination.

**Comment by stevepiercy** [comment]
@blaflamme would you take a crack at this one? I've never had to deal with long drop-down menus like this before. I tried various combinations of min-height, height, position:relative/absolute, clear:both, etc., but I couldn't get the right combination.

**Comment by blaflamme** [comment]
@stevepiercy fixed here https://github.com/Pylons/trypyramid.com/tree/ejs-ify

**Comment by blaflamme** [comment]
Done
