### ISSUE TITLE
TryPyramid.com is not responsive

### ISSUE THREAD

**Issue by kkinder** [Pylons/trypyramid.com#136]
Here's a [screenshot](http://i.imgur.com/746tuvC.png) of it on Android (Firefox). It looks much the same in Chrome. Although it is perhaps hard to see from the screenshot, on an actual mobile device:

- The top navigation, which has been activated, is far too small to use without a fine-tipped stylus.
- All of the text, but in particular the code samples, is in a font much too small to comfortably read.
- The huge margins on each side, which enhancing readability on a larger display, just further constrain the usable space of a small screen.

Similarly, if you [navigate to Extending Pyramid](https://trypyramid.com/resources-extending-pyramid.html), you'll notice that even on mobile devices, the margins continue to be outsized and there's still a grid of two, which necessitates panning and zooming to read.

**Comment by blaflamme** [comment]
@kkinder hmmm... good catch, the site is supposed to behave this way on a phone, thanks!

![screen shot 2016-05-31 at 9 30 46 am](https://cloud.githubusercontent.com/assets/454978/15676015/94cccf26-2712-11e6-8334-641b83f452be.png)

**Comment by blaflamme** [comment]
@kkinder fixed

**Comment by kkinder** [comment]
Nice.
