### ISSUE TITLE
Every page on TryPyramid.com has the same title

### ISSUE THREAD

**Issue by kkinder** [Pylons/trypyramid.com#137]
At the time of submitting this ticket, the following URLs all have _exactly_ the same title:
- https://trypyramid.com/
- https://trypyramid.com/resources.html
- https://trypyramid.com/resources-extending-pyramid.html

Giving each page on a site the same title is bad for several reasons:
1. It is poor search engine optimization. I'm not sure whether Google automatically dings websites for the practice, but either way, if you search for something like "Resources for Extending Pyramid", the _Extending Pyramid_ page should popup. However, if Google uses the title as-is, it will read on the search results page, "Welcome to Pyramid."
2. Additionally, just now, in trying to find that page in my browser history, I could only find it by URL. All the TryPyramid.com pages in my browser history had the exact same title.
3. If I were to bookmark any of these pages, to make them useful, I'd have to create a new title myself.

**Comment by blaflamme** [comment]
@kkinder you're right. In fact this site is a WIP and was not intended to be reddited as a final one in its current shape. OTOH that's cool to hear people POV, analyse and suggestions.

**Comment by stevepiercy** [comment]
Closed by #206
