### ISSUE TITLE
Navigation on Android not responsive

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#138]
![screenshot_2016-05-31-09-17-02](https://cloud.githubusercontent.com/assets/102112/15682153/31e14b4a-2711-11e6-829e-917de177038d.png)
![screenshot_2016-05-31-09-16-38](https://cloud.githubusercontent.com/assets/102112/15682160/3cc561d6-2711-11e6-892c-1a50e25739da.png)
![screenshot_2016-05-31-09-16-28](https://cloud.githubusercontent.com/assets/102112/15682165/41154b84-2711-11e6-8fd0-eedb01da6dbe.png)

**Comment by blaflamme** [comment]
@stevepiercy I've done a few fixes on the nav, mostly about transparency and colors, but at first the nav was not intended to be list of rows. We would need that when we add more menus.

**Comment by stevepiercy** [comment]
Things have improved with transparency, but there exist some usability issues:

1. The white hamburger disappears into a white background when scrolling down the page or on a secondary page. It appears on hover or touch.
2. Clicking the hamburger shows the menu as a horizontal list of vertical lists. The display should be vertical list of vertical lists, nested within each other.

I don't know of a good plugin that will handle this.

**Comment by stevepiercy** [comment]
Fixed in commits 90a953d9c684d03646efbb3e248ef38f039bcc01 and 873677073cb2eb95de599a172ce0b4a129129d7b.
