### ISSUE TITLE
Add OpenCIOC to Powered by Pyramid

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#139]
https://github.com/OpenCIOC/openciocdotorg/blob/master/img/cioc_logo_open_sm.png

**Comment by uralbash** [comment]
@stevepiercy Perhaps it will also be interesting for you https://github.com/nextgis/nextgisweb

**Comment by stevepiercy** [comment]
@uralbash please comment on a new issue #140

**Comment by stevepiercy** [comment]
Done in PR #160. This will be deployed when the new branch https://github.com/Pylons/trypyramid.com/tree/page-community is merged in to master in the next day or two.

**Comment by stevepiercy** [comment]
Closed by #165 and deployed. https://trypyramid.com/community-powered-by-pyramid.html
