### ISSUE TITLE
Add NextGIS to Powered by Pyramid

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#140]
@uralbash please provide the following if available.

* entity name
* entity category: company|organization|open source project
* description
* logo
* project URL
* demo URL
* pypi URL
* version control URL

**Comment by uralbash** [comment]
* entity name: NextGIS Web
* entity category: open source project with commercial support
* description: NextGIS Web is an opensource server-side Web GIS and a framework for storage, visualization and permissions management to all kinds of geodata. NextGIS Web supports OGC WMS and WFS(-T) access.
* logo: http://nextgis.com/wp-content/themes/nextgis_clean/img/logo.svg
* project URL: http://nextgis.com/nextgis-web/
* demo URL
* pypi URL: 
* version control URL: https://github.com/nextgis/nextgisweb

@drnextgis better knows the answers

**Comment by simgislab** [comment]
thanks for bringing it up!

logo (if you meant product logo, not company logo): 
[NGWeb_logo.svg.zip](https://github.com/Pylons/trypyramid.com/files/296044/NGWeb_logo.svg.zip)

demo URL: http://nextgis.com

**Comment by stevepiercy** [comment]
@simgislab  We can do two listings: one for the company and another for the open source project.

**Comment by simgislab** [comment]
great, I'll be happy to fill one for company too, if you can give me bullets

NGW above looks nice, thanks @uralbash

**Comment by stevepiercy** [comment]
@simgislab same as above: https://github.com/Pylons/trypyramid.com/issues/140#issue-158102450

**Comment by simgislab** [comment]
ah, right, here goes:

- entity name: NextGIS
- entity category: company
- description: Opensource geospatial solutions provider. Full stack: NextGIS Web/Mobile/Manager/QGIS
- logo: http://nextgis.com/wp-content/themes/nextgis_clean/img/logo.svg
- project URL: http://nextgis.com
- demo URL
- pypi URL:
- version control URL: https://github.com/nextgis

**Comment by stevepiercy** [comment]
Done in PR #161. This will be deployed when the new branch https://github.com/Pylons/trypyramid.com/tree/page-community is merged in to master in the next day or two.

**Comment by stevepiercy** [comment]
Closed by #165 and deployed. https://trypyramid.com/community-powered-by-pyramid.html

**Comment by drnextgis** [comment]
Thanks! But it looks strange:
![screenshot from 2016-06-15 05 17 21](https://cloud.githubusercontent.com/assets/866124/16061693/9425deee-32b8-11e6-89e2-8e88491f807e.png)

**Comment by stevepiercy** [comment]
@drnextgis I suspect server caching is causing the issue. Try force reloading. If it persists, please open a new issue.

**Comment by blaflamme** [comment]
I tried a fix but it seems somehow the responsive images give an hard time to isotope to figure out the height and then screw up the layout.

**Comment by stevepiercy** [comment]
@blaflamme maybe both isotope and img responsive class?
