### ISSUE TITLE
Media - Artwork

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#159]
@blaflamme I am ready for the final section of the website, Media, but I need updated artwork before I can proceed. We can't use the old orange Pyramid logo on the new site.

Based on the following:
- http://docs.pylonsproject.org/en/latest/promote/logos.html#pyramid-logo
- http://docs.pylonsproject.org/en/latest/promote/badges.html
- http://docs.pylonsproject.org/en/latest/promote/desktops.html

I would like to have the following:
- Pyramid logo, in PNG and SVG, for dark and light backgrounds
- Powered by Pyramid badges, in PNG and SVG, for dark and light backgrounds
- Pyramid desktop images

Thank you!

**Comment by stevepiercy** [comment]
See #37 for sample Powered by Pyramid buttons.

@blaflamme what needs to be done? I'll do the work, just need the original vector artwork. Else I'll recreate from scratch.

**Comment by blaflamme** [comment]
@stevepiercy need to find on a backup

**Comment by zupo** [comment]
@domenkozar brought 4 (5?) "not built by aliens" posters to DragonSprint and everyone is salivating over them. Can we get them in wallpaper form and upload them to the site?

**Comment by blaflamme** [comment]
@zupo this is something possible but they'll need to be reworked a bit since the format is not the same. I'll talk with Felix about how we can make them optimized as wallpapers.

**Comment by stevepiercy** [comment]
Preliminary work is on the branch [media-v4](https://github.com/Pylons/trypyramid.com/tree/media-v4)

**Comment by stevepiercy** [comment]
@blaflamme I noticed that there are subtle variations in the red in the Pyramid logo and blues in the Pylons Project logo that you sent me recently. I vaguely recall you mentioned something like Illustrator does not export colors correctly to PNG. Can you please fill in the correct values? Otherwise, can you say which file should be the authoritative file from which I should pick the correct colors? Thank you!

## Pyramid Red
* Hex: #bf343e
* RGB: 191, 52, 62
* HSL: 356°, 73%, 75%
* CMYK: 7%, 91%, 72%, 9%

## Pylons Project Dark Blue
* Hex: #214A88
* RGB: 33, 74, 136
* HSL: 217°, 81%, 56%
* CMYK: 95%, 74%, 2%, 4%

## Pylons Project Light Blue
* Hex: #1A76BB
* RGB: 26, 118, 187
* HSL: 206°, 86%, 73%
* CMYK: 81%, 45%, 1%, 1%

**Comment by stevepiercy** [comment]
Sketch was off after importing the master AI files. Here's what I got opening them in an AI CS4:

## Pyramid Red
* Hex: #be1e2d
* RGB: 190, 30, 45
* HSL: 354.38°, 84.21%, 74.51%
* CMYK: 15%, 100%, 90%, 10%

## Pylons Project Dark Blue
* Hex: #1b478f
* RGB: 27, 71, 143
* HSL: 217.24°, 81.12%, 56.08%
* CMYK: 99.46%, 83.13%, 12.09%, 1.9%

## Pylons Project Light Blue
* Hex: #1b75bb
* RGB: 27, 117, 187
* HSL: 206.25°, 85.56%, 73.33%
* CMYK: 85.1%, 49.95%, 0.43%, 0%

**Comment by blaflamme** [comment]
@stevepiercy I'll post my results after opening with Creative Cloud

**Comment by blaflamme** [comment]
@stevepiercy your last numbers looks right, with small differences, like 0.01% so bot a big deal.

**Comment by stevepiercy** [comment]
@blaflamme thanks for confirming.

**Comment by stevepiercy** [comment]
Closed by #224
