### ISSUE TITLE
Footer content suggestions

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#16]
- [x] Add links for [Agendaless Consulting](http://agendaless.com/) and [Pylons Project](http://www.pylonsproject.org/).
- [x] Make the current year dynamic instead of hard-coded 2015.

**Comment by stevepiercy** [comment]
I don't know where to add code to make the current year dynamic. Here's a reference to the Jinja docs on [Custom Filters](http://jinja.pocoo.org/docs/dev/api/#custom-filters). Maybe it's better to use webpack?

**Comment by stevepiercy** [comment]
After a conversation with @ergo in IRC, we've learned we don't know swig. We've both tried to add variables and use them in templates but had no luck. We've both read swig's docs on the matter https://paularmstrong.github.io/swig/docs/#variables and https://www.npmjs.com/package/swig-webpack-plugin I'm assigning this to Blaise to provide direction.

**Comment by blaflamme** [comment]
swig is going nowhere and I moved over [ejs](http://ejs.co), date is now dynamic.

**Comment by ergo** [comment]
One would think that actual pyramid + jinja2 would do the job well ;-)

**Comment by blaflamme** [comment]
templating stuff is still templating stuff... nothing exciting, just convenience. No need here for a backend app and IMHO if there's a need it should be for an API feeding a client app.

**Comment by stevepiercy** [comment]
YAY!

Remember to cleanup:

```
npm uninstall swig-webpack-plugin
```

**Comment by blaflamme** [comment]
@stevepiercy you can `rm -Rf node_modules` and start fresh
