### ISSUE TITLE
New company listing 

### ISSUE THREAD

**Issue by jgelens** [Pylons/trypyramid.com#167]
We're using Pyramid for most of our projects. Also I'll add a separate project listing later for our main (still unannounced product).

entity name: Noppo
entity category: company
logo: https://www.noppo.pro/images/logo-large.png 
URL: https://www.noppo.pro

**Comment by stevepiercy** [comment]
@jgelens Thank you! This will be pushed out with the next deployment, but I'll wait for your other listing to do so, unless we need to do another deployment sooner.
