### ISSUE TITLE
Add Lex Machina to Pyramid Powered

### ISSUE THREAD

**Issue by gcarothers** [Pylons/trypyramid.com#170]
entity name: Lex Machina
entity category: company
description: We mine litigation data, revealing insights never before available about judges, lawyers, parties, and patents, culled from millions of pages of litigation information.
logo: https://lexmachina.com/wp-content/uploads/2016/02/logo2016.png
project URL: https://lexmachina.com/
demo URL: https://law.lexmachina.com/
version control URL: https://github.com/LexMachinaInc/

**Comment by miohtama** [comment]
FYI Demo page seems to be authenticated only and doesn't mention how to get a demo account?

**Comment by gcarothers** [comment]
Yeah, welcome to SERIOUSLY niche software :D Not sure it's worth linking to the demo. There isn't much public facing to show. Might have a judge analytics page that will work in the future https://law.lexmachina.com/shared/eyJzaGFyZWRfcGFnZV9pZCI6NTUwN
30.CkNVNA.jU1fkzw0gLuggC78NDpbExtVJMQ but that URL is time limited right now.

**Comment by stevepiercy** [comment]
I've included all the provided data in the JSON object used in the page, although this page does not yet render all the data for companies and organizations. We have a few design issues in our queue, but the data is there when we solve them.

**Comment by stevepiercy** [comment]
@gcarothers if you have a larger logo or vector artwork of it, that would be helpful. I'll use the provided logo for now.

**Comment by stevepiercy** [comment]
This will be deployed on the next release. Thank you!
