### ISSUE TITLE
Create a robots.txt file

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#183]
We need a `robots.txt` file for SEO.

``` text
User-Agent: *
Allow: /
```

**Comment by bertjwregeer** [comment]
That `robots.txt` is the default. So not having one shouldn't be hurting anything.

**Comment by stevepiercy** [comment]
Visit:
https://trypyramid.com/robots.txt

It really should return the above content, not the home page, or a 404. This is also not right:
https://trypyramid.com/wompwomp.pitwee!

**Comment by bertjwregeer** [comment]
Hmm, that is bad...

**Comment by blaflamme** [comment]
Probably something wrong with the nginx config file, will take a look.
