### ISSUE TITLE
Let's Encrypt certificate should auto-renew

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#187]
Ping @blaflamme. Our certificate Let's Encrypt has expired. I just configured LE for my virtual host and set up a cron job, using [certbot](https://certbot.eff.org/). Let me know if you need help.

**Comment by blaflamme** [comment]
@stevepiercy it has been working for previous renewals so something has probably changed. It looks like certbot is the new client, then I'll update to the new client. Thanks for pointing out.

**Comment by blaflamme** [comment]
looking at the logs...
```
You are running with an old copy of letsencrypt-auto that does not
receive updates, and is less reliable than more recent versions. We
recommend upgrading to the latest certbot-auto script, or using
native OS packages.
```
then I did the update manually for now and will install the new certbot later.

**Comment by stevepiercy** [comment]
There is one gotcha with certbot that bit me. Every virtual host must have its own .conf file, and one each for ports 80 and 443. See:
https://github.com/certbot/certbot/issues/2776#issuecomment-210782032

Also make sure you back up your conf files before running certbot-auto.

**Comment by blaflamme** [comment]
@stevepiercy this issue seems related to apache, I'm using nginx with webroot module. I'm already using a separate config file per vhosts but including both :80 & :443 in the same config. I'll see when moving to certbot.

**Comment by bertjwregeer** [comment]
I use letsencrypt.sh...

With an NGINX config with a vhost per :443, but a single :80 that only serves up the challenge/response.

It's a shell script using only OpenSSL commands and the like, makes it easy to audit and is very simple to use.
