### ISSUE TITLE
Adding Snapsat to Powered by Pyramid 

### ISSUE THREAD

**Issue by Jakeand3rson** [Pylons/trypyramid.com#188]
entity name: Snapsat
entity category:
[ ] company
[•] organization
[•] free and libre open source project or application
[•] website
description: We're in love with the opensource geospatial movement, and we wanted to contribute something back to it. Landsat is an amazing program — we wanted to make it accessible to anyone, regardless of their technical background.
maintainers: Constantine Hatzis, Joel Stanner, Mark Saiget, Jake Anderson, Jacques Tardie
logo: https://avatars.githubusercontent.com/u/11448531?size=100
project URL: http://snapsat.org/
demo URL: http://snapsat.org/guide/#walkthrough
pypi URL:
version control URL: https://github.com/recombinators
 

Wow this has taken me entirely too long to post. I met y'all at Pycon and was invited to fill this out to get on the website. If you have any questions please hit us up at Snapsat@snapsat.org !

**Comment by stevepiercy** [comment]
Thank you! I've added you to the page under Applications as that seemed to be the best fit. If you prefer a different or additional section, please let me know.
https://trypyramid.com/community-powered-by-pyramid.html
