### ISSUE TITLE
Add Atramhasis to Powered by Pyramid

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#190]
Pulled from an obsolete wiki page.

Ping @OnroerendErfgoed. The demo app does not respond.

# Atramhasis
![Atranhasis](https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/static/img/atramlogo.png?raw=true)

* Description : Atramhasis is an online SKOS editor. This webapplication enables users to create SKOS vocabularies consisting of Concepts and Collections. It tries to stay close to the SKOS specification. This makes it suited for different types of vocabularies such as simple pick lists, authority files, flat lists and basic to relatively complex thesauri. Atramhasis is not suited for managing very large or complex thesauri such as the AAT.
* Repository: https://github.com/OnroerendErfgoed/atramhasis
* Documentation: http://atramhasis.readthedocs.org/
* Demonstration: http://glacial-bastion-1106.herokuapp.com/

**Comment by maarten-vermeyen** [comment]
@stevepiercy Thanks. The demo server uses the free hosting option on Heroku. It shuts down after 30 minutes of inactivity. It only starts up again when someone makes another request, takes about 60 seconds.
