### ISSUE TITLE
Add Events subsection to Sponsors

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#196]
Linode is one sponsor, and it currently is shown in the footer sitewide, but its presentation is easy to miss. It would be good to show them a little more thanks by showing their logo or featuring them more prominently.

We also might want to add a sponsors page.

**Comment by zupo** [comment]
I'd like to see Community -> Pharaos (or some funny pyramid related name) for listing sponsors and supporters. Since PSF/PloneFoundation supported dragonsprint.com we might also add them to the list.

**Comment by stevepiercy** [comment]
There's a new Sponsors page under Community.
https://trypyramid.com/community-sponsors.html

We can have a subsection for Events, and add Plone, PSF, and other sponsors( @zupo should all of them get credit?) for http://dragonsprint.com/. It might encourage more sponsoring of events.

**Comment by zupo** [comment]
@stevepiercy: yep, all

+1 for having events subsection

**Comment by stevepiercy** [comment]
I broke this into two separate pages https://trypyramid.com/community-sponsors.html and https://trypyramid.com/community-events.html
