### ISSUE TITLE
Template to add items to Extending Pyramid

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#202]
Add your project to the [Extending Pyramid page](https://trypyramid.com/extending-pyramid.html) on TryPyramid.com, providing the following information by submitting a [New Issue](https://github.com/Pylons/trypyramid.com/issues/new):
- project name
- project URL
- description
- maintainers
- PyPI URL
- VCS URL
- docs URL
- demo URL
- support (select one):
  - [ ] Official Pylons Project
  - [ ] Community
  - [ ] Unsupported
- addon (select one):
  - [ ] Yes
  - [ ] No
- category (select at least one but don't go crazy, or suggest a new category):
  - [ ] api
  - [ ] asset-management
  - [ ] async
  - [ ] authentication
  - [ ] authorization
  - [ ] caching-and-sessions
  - [ ] configuration
  - [ ] debugging
  - [ ] development-environment
  - [ ] documentation
  - [ ] email
  - [ ] forms
  - [ ] internationalization-i18n
  - [ ] media-management
  - [ ] monitors
  - [ ] renderers
  - [ ] requests
  - [ ] routes
  - [ ] routing
  - [ ] scaffolds
  - [ ] search
  - [ ] services
  - [ ] sessions
  - [ ] storage
  - [ ] task-queueing
  - [ ] template-languages
  - [ ] testing
  - [ ] url-shorteners-and-managers
  - [ ] user-interface-and-user-experience-ui-and-ux
  - [ ] web-page-utilities
  - [ ] wsgi-servers
- tags (comma-separated list for search engines)

**Comment by Dowwie** [comment]
project name:  pyramid_yosai
project URL:  https://yosaiproject.github.io/yosai/

description:  Yosai is a security framework that offers two-factor authentication, permission and role based authorization, and session management from a developer-friendly API.  pyramid_yosai integrates yosai with pyramid web applications.

maintainers:  Darin Gordon
PyPI URL:  https://github.com/yosaiproject
VCS URL:  https://github.com/YosaiProject/pyramid_yosai
docs URL:  https://yosaiproject.github.io/yosai/

categories:  authentication, authorization, session management
