### ISSUE TITLE
pyramid_yosai add-ons

### ISSUE THREAD

**Issue by Dowwie** [Pylons/trypyramid.com#203]
project name: pyramid_yosai
project URL: https://yosaiproject.github.io/yosai/

description: Yosai is a security framework that offers two-factor authentication, permission and role based authorization, and session management from a developer-friendly API. pyramid_yosai integrates yosai with pyramid web applications.

maintainers: Darin Gordon
PyPI URL: https://github.com/yosaiproject
VCS URL: https://github.com/YosaiProject/pyramid_yosai
docs URL: https://yosaiproject.github.io/yosai/

categories: authentication, authorization, session management

**Comment by stevepiercy** [comment]
Closed in #204
