### ISSUE TITLE
Add Media page

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#21]
- [x] Create page, add to nav, etc.
- [x] Twitter widget
- [x] Google Group widget
- [ ] GitHub widget (blocked)
- [x] Choose Twitter handle and update widget

**Comment by stevepiercy** [comment]
Do we have content for this item?

**Comment by pauleveritt** [comment]
It was first conceived two years ago. I suspect we’ve had some new things happen since then. :)

Of course, “news” pages are chronic sore spots in projects. When the newest news is a year old, it’s embarrassing. We can choose to axe this.

—Paul

**Comment by stevepiercy** [comment]
Agreed. The closest thing to "news" we have is when we make announcements of releases, and I think we do that more effectively under the new Resources page.

Instead I propose another page to consist of tweets, Google Group posts to pylons-discuss, podcasts, and any other online media mentions. Suggest the name "Media", which translates fairly easily to other languages and cultures and has an implicit context of "Social Media" and "Press Release".

**Comment by pauleveritt** [comment]
Is the idea that these are JS widgets that automatically pull in the information? If not, then we’re back to a hand-curated News section.

—Paul

**Comment by stevepiercy** [comment]
[Twitter](https://dev.twitter.com/web/overview) and posts from [Google Groups](https://support.google.com/groups/answer/1191206?hl=en) can be JS widgets.

I don't know of any other JS widgets for podcasts or other media mentions, so I think those would have to be hand-curated, if we go that route.

**Comment by stevepiercy** [comment]
BTW, my proposal at this point is to use the name "Media" for a new page that contains only tweets (of whatever Twitter handle we choose) and pylons-discuss posts as JS widgets, and nothing else.

**Comment by pauleveritt** [comment]
I like the name “Media”. I think if you can get Twitter and Google Groups (and perhaps GitHub commits?) as widgets, then it completely alleviates the it-gets-stale argument. Good thinking.

—Paul

**Comment by stevepiercy** [comment]
See my private email regarding the Twitter handle.

I can get Google Groups for pylons-discuss.

I don't know of any GitHub JS widget.

**Comment by pauleveritt** [comment]
It’s old, but perhaps this GitHub commits widget still works:

  https://github.com/alexbeletsky/github-commits-widget

—Paul

**Comment by stevepiercy** [comment]
I think I've gone as far as I can with the access I have to the various sources for widgets.

**Comment by stevepiercy** [comment]
The Google Group widget does not work for me on localhost:

> Refused to display 'https://groups.google.com/forum/embed/?place=forum/pylons-discuss&showsearch=true&showpopout=true&parenturl=http%3A%2F%2Flocalhost%3A8080%2Fmedia.html' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

The Google Group help suggests that if it does not work, then add the website's domain name, trypyramid.com in this case, once it is deployed. This one is in Blaise's hands.

I do not have access to @pylons. I think @goodwillcoding controls that account. So I used @trypyramid for the mockup.

I tried the GitHub widget Paul suggested, but it didn't work out of the box. I have a feeling this is not possible through javascript alone, but requires oauth and access to the Pylons GitHub account settings to create an Application or whatever they call it.

**Comment by goodwillcoding** [comment]
twitter widget:

    <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/pylons" data-widget-id="683880296756850688">Tweets by @pylons</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

**Comment by stevepiercy** [comment]
@goodwillcoding thanks, added in https://github.com/stevepiercy/trypyramid.com/commit/ff4ac17315d2f604e27fcb08d0026719123e28e4

**Comment by stevepiercy** [comment]
twitter handle is now @trypyramid, per https://github.com/stevepiercy/trypyramid.com/commit/466e55a8c5552b42c7d0a46b2d5015de14558751

**Comment by stevepiercy** [comment]
Closing. Work is on PR #45.
