### ISSUE TITLE
Remarkbox is Powered by Pyramid

### ISSUE THREAD

**Issue by russellballestrini** [Pylons/trypyramid.com#214]
<img src="http://www.remarkbox.com/remarkbox-minified.png">

entity name: Remarkbox
entity category: company

description:

``` 
Comments as a service

Readers want to communicate with you
  
Get Remarkbox, the comment system that engaged readers prefer to use!
``` 

maintainers: Russell Ballestrini
project URL: http://www.remarkbox.com/

logo: http://www.remarkbox.com/remarkbox-minified.png

**Comment by stevepiercy** [comment]
Thanks, @russellballestrini. I've added this, and updated the site.

**Comment by russellballestrini** [comment]
Thank you Steve! I review and it looks perfect.

**Comment by russellballestrini** [comment]
hey @stevepiercy I was just bragging today about Pyramid and went to show off how my project was listed and it wasn't : (  

Any clue what happened?

**Comment by stevepiercy** [comment]
@russellballestrini you're right, it's vanished. I'll take a look tonight to see what happened and restore it. Sorry about that, and thanks for letting me know.

**Comment by bertjwregeer** [comment]
It looks like this commit made it disappear: https://github.com/Pylons/trypyramid.com/commit/4bb758f443bed7679514853470d612260db20d5d#diff-da2be9a2a2b03f945a1398a4417d556a

alongside NASA

**Comment by stevepiercy** [comment]
This is now fixed in https://github.com/Pylons/trypyramid.com/commit/336d34581813a48f84dbe49b2a6411aed3f488bd. I also restored NASA and Rollbar. I suspect it was from a bad database migration months ago.
https://trypyramid.com/community-powered-by-pyramid.html

**Comment by russellballestrini** [comment]
@stevepiercy thank you very much!
