### ISSUE TITLE
Add Powered by Pyramid page

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#22]
- [x] Pull content from wiki pages:
https://github.com/Pylons/pyramid/wiki/Companies-and-organizations-that-use-Pyramid
https://github.com/Pylons/pyramid/wiki/Projects-that-use-Pyramid
And slider on home page of PP.org:
https://github.com/Pylons/pylonshq/blob/master/pylonshq/templates/home/home.mako#L79-L118
- [x] Come up with a better name for the page than "Who's Using Pyramid"
- [x] Determine which companies actually use Pyramid from this list https://github.com/Pylons/trypyramid.com/issues/22#issuecomment-168612083 @goodwillcoding 
- [x] Hunt down high quality logos. @stevepiercy
- [x] Update content with logos. @stevepiercy
- [ ] Design layout for content. @blaflamme

**Comment by stevepiercy** [comment]
Can we come up with a better name than "Who's Using Pyramid"? It's klunky. Maybe "Mummies", "Not Aliens".

**Comment by pauleveritt** [comment]
I agree that’s a mouthful, but Mummies and Not Aliens aren’t really aimed at the target market for this site. Perhaps we should look around at some other sites and see what they do.

djangoproject.com doesn’t have anything.

python.org has it under “Community -> Success Stories”.

—Paul

**Comment by stevepiercy** [comment]
Flask uses "Powered by Flask". I changed to "Powered by Pyramid" because I like me some alliteration.

**Comment by stevepiercy** [comment]
Ready for @blaflamme to work his magic. I can round up better logos. I also need to verify who is and is not using Pyramid. I think most of those companies use Pylons and not Pyramid.

**Comment by blaflamme** [comment]
ideally we should ask them for vector or large png with transparency if we want to have some food to work with.

**Comment by stevepiercy** [comment]
@blaflamme of course! Do you have enough content to play with? If you can provide a template I'll do the grunt work of getting good images, resizing them, and dropping in content.

**Comment by stevepiercy** [comment]
Work for this item is in PR #30

**Comment by stevepiercy** [comment]
@goodwillcoding here is the list of companies that I compiled from the janky carousel on the pylonsproject.org home page and https://github.com/Pylons/pyramid/wiki/Companies-and-organizations-that-use-Pyramid 

Please verify which of the companies from pylonsproject.org actually use Pyramid and not Pylons. I have verified the ones from the wiki already. Thank you!

# Companies and Organizations
## from wiki
* https://hypothes.is/
* http://www.discnw.org
* http://www.zopyx.com
* https://www.majerti.fr
* http://itcase.pro
* http://kleinundpartner.at/
* http://www.adroll.com/
* http://getbirdseye.com/

## from pylonsproject.org
* http://buzzumi.com/
* http://www.bittorrent.com/
* http://www.newcars.com/
* http://digg.com/
* https://www.dropbox.com/
* http://www.freshbooks.com/
* http://www.imagemoversdigital.com/
* http://www.lolapps.com/
* http://www.mochimedia.com/
* http://www.opera.com/
* http://oreilly.com/
* http://saucelabs.com/
* http://www.reddit.com/
* http://sourceforge.net/
* http://www.surveymonkey.com/
* http://www.tineye.com/
* http://www.wetafx.co.nz/
* http://www.netsight.co.uk/

# Projects
* Autonomie https://github.com/CroissanceCommune/autonomie

**Comment by stevepiercy** [comment]
from @stevepiercy at SFPython meetups
* http://www.yelp.com/
* https://www.mozilla.org/

**Comment by Jeremydavisvt** [comment]
[Reading Plus](https://readingplus.com) (where I work) has about 3 projects in Pyramid. Most notably the Explorer project (internal tool) and Salesdash (for internal and external sales partners)

[PCBlueprint](https://readingplus.com) (my project) uses Pyramid

**Comment by stevepiercy** [comment]
@Jeremydavisvt thank you! I've updated the list above.

**Comment by ergo** [comment]
There is also:
https://appenlight.com
https://rhodecode.com

**Comment by stevepiercy** [comment]
Thanks @ergo! If you have better logos, please provide links or artwork.

**Comment by stevepiercy** [comment]
@blaflamme it's not clear how to add static images to the site in the readme. Can you elaborate? I've tried adding new logos to `src`, building using npm, but it appears that the images are not copied to `build`, as I would expect. In my personal wepback config in other projects, I "shell out" and just use `cp` for that. Please let me know how you think it best to manage images.

**Comment by stevepiercy** [comment]
@blaflamme I found that I needed to add each image as a require in `src/main.js` and in the HTML.

**Comment by stevepiercy** [comment]
I was just reminded of this repo https://github.com/uralbash/awesome-pyramid as a source of Powered by Pyramid items.

**Comment by stevepiercy** [comment]
I've pushed a commit for any relevant Powered by Pyramid items from https://github.com/uralbash/awesome-pyramid to PR #46. It's all up to you @blaflamme

**Comment by stevepiercy** [comment]
Closing. Work is in PR #46
