### ISSUE TITLE
Add Rollbar listing

### ISSUE THREAD

**Issue by jessewgibbs** [Pylons/trypyramid.com#220]
entity name: Rollbar
entity category (choose one): Company
description:  Rollbar provides developers with full-stack error monitoring and alerting as a service
logo (will be resized to 700x200 pixels (HxW): https://rollbar.com/assets/homepage/images/media/png/rollbar-logo-color-horiz.png
project URL: https://rollbar.com
demo URL: https://rollbar.com/demo/demo/

**Comment by stevepiercy** [comment]
Deployed in https://github.com/Pylons/trypyramid.com/commit/714eea0a3e7ddc34ede5a9e7f210020b87f0fb9c:
https://trypyramid.com/community-powered-by-pyramid.html
