### ISSUE TITLE
pyramid_retry

### ISSUE THREAD

**Issue by mmerickel** [Pylons/trypyramid.com#222]
Project name: pyramid_retry
Project url: http://docs.pylonsproject.org/projects/pyramid-retry/en/latest/
Description: An execution policy for Pyramid that supports retrying requests after certain failure exceptions.
Maintainers: Michael Merickel
PyPI url: https://pypi.python.org/pypi/pyramid-retry
VCS url: https://github.com/Pylons/pyramid_retry
Docs url: http://docs.pylonsproject.org/projects/pyramid-retry/en/latest/
Support: official
Addon: yes
Category: routing?

**Comment by stevepiercy** [comment]
Closed by 7804bdc7b92202b0ce0ef2459490a3e49eda8e00
