### ISSUE TITLE
Add Pyramid OpenTracing tween

### ISSUE THREAD

**Issue by carlosalberto** [Pylons/trypyramid.com#223]
Project name: pyramid-opentracing
Project url: https://github.com/carlosalberto/python-pyramid
Description: OpenTracing library/tween for tracing/integration of Pyramid's requests.
Maintainers: Carlos Alberto Cortez (https://github.com/carlosalberto)
PyPi: https://pypi.python.org/pypi/pyramid-opentracing/
VCS: https://github.com/carlosalberto/python-pyramid
Docs: https://github.com/carlosalberto/python-pyramid
Demo url: Not available
Support: Unsupported
Addon: Yes
Category: debugging
Tags: opentracing, pyramid, python

**Comment by stevepiercy** [comment]
Added! Thank you!
https://trypyramid.com/resources-extending-pyramid.html
