### ISSUE TITLE
Submit and administer Powered by Pyramid and Add-on entries

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#226]
Currently when someone wants to add their item to [Powered by Pyramid](https://trypyramid.com/community-powered-by-pyramid.html) or [Extending Pyramid](https://trypyramid.com/resources-extending-pyramid.html), the process is tedious and manual.

1. Use a template to submit a new issue:
  - [Template to add items to Powered by Pyramid](https://github.com/Pylons/trypyramid.com/issues/162)
  - [Template to add items to Extending Pyramid](https://github.com/Pylons/trypyramid.com/issues/202)
2. Steve Piercy add the item to a database.
3. Steve Piercy run a script to export the items to JSON.
4. Steve Piercy update the appropriate .json file in the repo.
5. Steve Piercy [make a new release](https://github.com/Pylons/trypyramid.com/blob/master/RELEASE.md).

The following is a proposal to avoid all that tedium.

Authentication would use [GitHub's API for OAuth](https://developer.github.com/v3/oauth/) to identify a user, so that we don't have to deal with usernames, passwords, and resetting passwords.

Ideally there would be a form for the user to submit their request along with uploading any artwork.

The system would validate the data, create a record, resize the image to the appropriate size, [create an issue on GitHub](https://developer.github.com/v3/issues/#create-an-issue), and notify designated admins that a new item has been submitted (this notification may be redundant to the issue creation, since GitHub sends notifications when an issue is created).

An admin would login, review the submission, and either approve, ask questions, or reject it. For all actions, both the database and GitHub issue would be updated.

If approved, the record would be displayed.

**Comment by bertjwregeer** [comment]
Add-ons are now simple YAML files, and the build has been automated. This makes it much easier to add new addons and entries while not complicating matters.
