### ISSUE TITLE
Clarify status of trypyramid.com website, pyramid brand (if any) etc

### ISSUE THREAD

**Issue by corehack** [Pylons/trypyramid.com#232]
There's a note in the footer which I find a bit confusing:
`© Copyright 2008-2017, Agendaless Consulting`

It makes impression this is a corporate-owned website. I am sure it can confuse #people:
- is this really a community website ?
- what is this website marketing, the framework or the services of Agendaless Consulting ?
- if I join the community, am I serving public interest or an interest of a corporate entity ?
... etc

I understand that there's some copyright involved in many parts of the pyramid itself and maybe this website, but in general it should not be presented like this if you want random people from the internet getting involved

**Comment by stevepiercy** [comment]
See http://pylonsproject.org/community-how-to-contribute.html.

**Comment by corehack** [comment]
Sorry maybe I wasn't clear enough. I didn't mean "explain it to me", but rather "make it obvious for any visitor of the website".

**Comment by corehack** [comment]
Besides, you are not affiliated with Agendaless Consulting. We need official response

**Comment by stevepiercy** [comment]
The points you raise are beyond the scope of the single project trypyramid.com, a marketing website for Pyramid, which is but one small project of the Pylons Project organization. Your points would impact *all* projects under the organization.

Moreover, there are only a handful of people who watch this repo's issue tracker, whereas the pylons-discuss email list has a almost 2900 subscribers, many who have expertise in organizational and legal matters. Additionally, some of your points might be better addressed directly to the principals of Agendaless Consulting.

**Comment by corehack** [comment]
Steve, I really appreciate your work. I got your point so I posted on the mailing list
Best wishes.
