### ISSUE TITLE
Add pyramid-log to "Extending Pyramid" listing

### ISSUE THREAD

**Issue by dairiki** [Pylons/trypyramid.com#236]
Please consider [pyramid-log](https://pypi.python.org/pypi/pyramid-log/) for inclusion on the [Extending Pyramid](https://trypyramid.com/resources-extending-pyramid.html) page.
Thank you!

- project name:
  pyramid-log
- project URL:
  https://pypi.python.org/pypi/pyramid-log/
- description:
  A [logging formatter](https://docs.python.org/3/library/logging.html#formatter-objects) which makes Pyramid request attributes available for us in its format string.
- maintainers:
  Jeff Dairiki
- PyPI URL:
  https://pypi.python.org/pypi/pyramid-log/
- VCS URL:
  https://github.com/dairiki/pyramid_log
- docs URL
- demo URL
- support (select one):
  - [ ]  Official Pylons Project
  - [x]  Community
  - [ ]  Unsupported
- addon (select one):
  - [x]  Yes
  - [ ]  No
- category (select at least one but don't go crazy, or suggest a new category):
  - [ ]  api
  - [ ]  asset-management
  - [ ]  async
  - [ ]  authentication
  - [ ]  authorization
  - [ ]  caching-and-sessions
  - [ ]  configuration
  - [x]  debugging
  - [ ]  development-environment
  - [ ]  documentation
  - [ ]  email
  - [ ]  forms
  - [ ]  internationalization-i18n
  - [x]  *logging*
  - [ ]  media-management
  - [ ]  monitors
  - [ ]  renderers
  - [ ]  requests
  - [ ]  routes
  - [ ]  routing
  - [ ]  scaffolds
  - [ ]  search
  - [ ]  services
  - [ ]  sessions
  - [ ]  storage
  - [ ]  task-queueing
  - [ ]  template-languages
  - [ ]  testing
  - [ ]  url-shorteners-and-managers
  - [ ]  user-interface-and-user-experience-ui-and-ux
  - [ ]  web-page-utilities
  - [ ]  wsgi-servers
- tags (comma-separated list for search engines): pyramid, logging

**Comment by stevepiercy** [comment]
Added in https://github.com/Pylons/trypyramid.com/commit/aeb76bea8382655a5a5e0802503d1d1d97e76985, then deployed.
https://trypyramid.com/resources-extending-pyramid.html

Thank you!
