### ISSUE TITLE
Extending Pyramid(A new scaffold)

### ISSUE THREAD

**Issue by asif-mahmud** [Pylons/trypyramid.com#239]
Hi,
I have been updating and maintaining a Pyramid scaffold here, on github. This scaffold focuses on the following aspects -

1.  Traversal based application
2. JSON only response
3. JWT authentication policy
4. Alembic for database revisions
5. Some simple modifications to base tests, views and models base to reduce typing

This is a very minimalistic scaffold that focuses on creating web api like backends. Very easy to create REST APIs with this scaffold. I myself have been using it for some time and now I feel I should share it with others. It is a [CookieCutter](https://cookiecutter.readthedocs.io/) scaffold and publicly available on github.

**Project name:** Pyramid Runner
**Project/VCS URL:** https://github.com/asif-mahmud/pyramid_runner
**Maintainers:** Asif Mahmud Shimon
**Support:** Community
**Addon:** no
**Category:** scaffolds

**Comment by stevepiercy** [comment]
Thank you! Closed by a45abe6b72be27a1db2807f86e756bc1e3ecb02c
