### ISSUE TITLE
Add pyramid_bugsnag to "Extending Pyramid"

### ISSUE THREAD

**Issue by pior** [Pylons/trypyramid.com#241]
👋  Please consider listing pyramid-bugsnag on trypyramid.com.

- Project name: pyramid-bugsnag
- Project url: https://github.com/pior/pyramid_bugsnag
- Description: Pyramid extension to configure and integrate the Bugsnag client
- Maintainers: Pior Bastida (https://github.com/pior)
- PyPi: https://pypi.python.org/pypi/pyramid-bugsnag/
- VCS: https://github.com/pior/pyramid_bugsnag
- Docs: https://github.com/pior/pyramid_bugsnag
- Demo url: N/A
- Support: Community
- Addon: No
- Category: debugging
- Tags: bugsnag, error, monitoring

**Comment by pior** [comment]
Maybe I could directly open a PR with the needed changes? 
@stevepiercy

**Comment by stevepiercy** [comment]
@pior sorry I missed your initial request. I'm traveling and will be back home in a day or two, then I will add your listing. Thank you for the follow up.

**Comment by stevepiercy** [comment]
Added in https://github.com/Pylons/trypyramid.com/commit/a2f433230a6a0a90bc85b64a49e6aef3236af8c2 and https://github.com/Pylons/trypyramid.com/commit/67b617ebccba7123ab096ba337add7270d7fdb4f
