### ISSUE TITLE
Add pyramid-jsonapi to "Extending Pyramid"

### ISSUE THREAD

**Issue by mrichar1** [Pylons/trypyramid.com#242]
* project name: pyramid-jsonapi
* project URL: https://github.com/colinhiggs/pyramid-jsonapi
* description: Create a JSON-API (http://jsonapi.org/) standard API from a database using the sqlAlchemy ORM and pyramid framework. Includes schema validation and documentation generation (OpenAPI).
* maintainers: Colin Higgs (https://github.com/colinhiggs)
* PyPI URL: https://pypi.python.org/pypi/pyramid_jsonapi
* VCS URL: https://github.com/colinhiggs/pyramid-jsonapi
* docs URL: https://colinhiggs.github.io/pyramid-jsonapi/
* support: Community
* addon : Yes
* category:
   *  api
  *  services
* tags: jsonapi, sqlalchemy, jsonschema, openapi

Thanks!

**Comment by stevepiercy** [comment]
Added in e2df1f772e1ef1ccd3dcd66da53a32a0b8e56cdf. Thank you!
