### ISSUE TITLE
VantagePoint PoweredBy 

### ISSUE THREAD

**Issue by danny248** [Pylons/trypyramid.com#243]
entity name: VantagePoint
entity category: Company
description: VantagePoint is a product designed to streamline your security operations. It does so by integrating multiple security products into a single platform and making deployment and management a simple exercise. Within minutes, you will get a true understanding of your overall security posture along with a real, actionable, and prioritized plans for remediating gaps. All of this is available on any operating system, at any scale, in any physical or virtual environment.
maintainers: VantagePoint
logo (will be resized to 700x200 pixels (HxW): See below
project URL: http://vantagepoint.co
trial URL: http://signup.vantagepoint.co

![vp_logo_dark_bcg](https://user-images.githubusercontent.com/3219750/35485919-f6b2e7dc-042b-11e8-8c1b-19dbd394ca90.jpg)

**Comment by stevepiercy** [comment]
Added!
https://trypyramid.com/community-powered-by-pyramid.html

Thank you!
