### ISSUE TITLE
Add pyramid_debugauth to "Extending Pyramid"

### ISSUE THREAD

**Issue by pior** [Pylons/trypyramid.com#244]
👋  Please consider listing pyramid_debugauth on trypyramid.com.

- Project name: pyramid_debugauth
- Project url: https://github.com/pior/pyramid_debugauth
- Description: Debug Authentication Policy for Pyramid
- Maintainers: Pior Bastida (https://github.com/pior)
- PyPi: https://pypi.python.org/pypi/pyramid_debugauth/
- VCS: https://github.com/pior/pyramid_debugauth
- Docs: https://github.com/pior/pyramid_debugauth
- Demo url: N/A
- Support: Community
- Addon: No
- Category: debugging
- Tags: authentication, error, monitoring

Ping @stevepiercy

**Comment by stevepiercy** [comment]
Added in fa69391968bab671a98dd767d2a85ff245d8cedf. Thank you!
