### ISSUE TITLE
Template to add items to Powered by Pyramid: charte.ca

### ISSUE THREAD

**Issue by showdep** [Pylons/trypyramid.com#246]
entity name: charte.ca
entity category: Company
description: Free online data visualization for non-techies and geeks. interactive chart editor, no coding or design skills required. Scalable graphics, pivot tables, drilldowns, cloud publishing, export, API.
maintainers: charte.ca
logo (700x200): See below
project URL: http://charte.ca
![charteca-logo-700x200](https://user-images.githubusercontent.com/853226/38526370-e9e6b558-3c0a-11e8-87ac-966c58c1c020.jpg)

**Comment by stevepiercy** [comment]
Thank you! Added https://trypyramid.com/community-powered-by-pyramid.html
