### ISSUE TITLE
Add CompareBench to Powered by Pyramid page

### ISSUE THREAD

**Issue by Jeremydavisvt** [Pylons/trypyramid.com#247]
entity name: CompareBench
entity category: website
description: A new platform that allows you to track all your existing benchmark results from Unigine Heaven to 3DMark. Share your entire build profile, or create comparisons with other build profiles.
maintainers: CompareBench team
logo (will be resized to 700x200 pixels (HxW): https://s3.amazonaws.com/cb-assets/logo.png
project URL: https://comparebench.com
demo URL: n/a
pypi URL: n/a
version control URL: n/a

**Comment by stevepiercy** [comment]
Done, and Tweeted: https://twitter.com/PylonsProject/status/986015056776196096

Thank you!
