### ISSUE TITLE
replace pypi.python.org link with pypi.org link

### ISSUE THREAD

**Issue by brainwane** [Pylons/trypyramid.com#248]
I noticed that `trypyramid.com/dist/resources-extending-pyramid.html` includes links to several pypi.python.org URLs. Per https://warehouse.readthedocs.io/api-reference/ and https://mail.python.org/pipermail/python-announce-list/2018-April/011893.html , pypi.python.org now redirects to pypi.org, which runs a new codebase. For most of those links (project URLs) the redirect will work fine, but `https://pypi.python.org/pypi?:action=browse&c=582` currently does not redirect, so you might want to replace that with a classifier search URL for pypi.org. If you want to test it and any other URLs you're using for classifier-based searches, you can use http://legacy.pypi.org/ , but that is shutting down on April 30th, so I would advise you to migrate soon.

Thank you!

**Comment by stevepiercy** [comment]
@brainwane thanks for the report!

I was looking at [python.org for these instances](https://github.com/python/pythondotorg/pull/1245), and forgot to check our own. 😊

**Comment by stevepiercy** [comment]
I hit webob.org, pylonsproject.org, trypyramid.com, and I'm about to hit docs for Pyramid. Thanks again for the reminder!
