### ISSUE TITLE
New Pyramid Module for mongodb

### ISSUE THREAD

**Issue by JonnoFTW** [Pylons/trypyramid.com#250]
I have a packages to add to the list (sorry for the poor project name, pyramid_mongo, pyramid_mongodb and pyramid_mongoengine are already taken):

* project name: pyramid_mongodb2
* project URL: https://pypi.org/project/pyramid_mongodb2/
* description: Provides a mongodb integration to with your pyramid app. Comes with a debugtoolbar and supports multiple databases.
* maintainers: jonno_ftw
* PyPI URL: https://pypi.org/project/pyramid_mongodb2/
* VCS URL:   https://github.com/JonnoFTW/pyramid_mongodb2
* docs URL: None
* demo URL: None
* support (select one):
  * Community
* addon (select one):
  *  No
* category (select at least one but don't go crazy, or suggest a new category):
   *  storage

**Comment by stevepiercy** [comment]
Done! Thank you!
