### ISSUE TITLE
Reorganize navigation to improve visibility of documentation

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#251]
Documentation is difficult to find on the site. Let's make it easier. First we need to make space in the navbar, which means a reorganization is needed.

- [x] [Media > Artwork](https://trypyramid.com/media-artwork.html): Move under Community and rename file to `community-artwork.html`
- [x] [Media > Feeds](https://trypyramid.com/media-feeds.html): Move under Community and rename file to `community-feeds.html`
- [x] Remove Media navigation item to make room for Add-ons.
- [x] [Resources > Extending Pyramid](https://trypyramid.com/resources-extending-pyramid.html): Move to "Add-ons" as a primary navigation menu item and rename file to `extending-pyramid.html`.
- [Resources > Core](https://trypyramid.com/resources.html)
    - [x] Rename "Pyramid web framework resources" in grey bar to "Pyramid web framework documentation"
    - [x] Rename "Resources > Core" to "Documentation" and promote to primary navigation menu item, replacing "Resources".
    - [x] Rename `resources.html` to `documentation.html`
- [x] Add redirects in nginx configuration for all renamed files
- [ ] Run linkcheck in Sphinx on Pyramid docs to find any redirects and fix as needed

**Comment by russellballestrini** [comment]
This will be a refreshing change!

**Comment by stevepiercy** [comment]
Ping @blaflamme for feedback. If I don't hear back after a week or so, I'll proceed as proposed.
