### ISSUE TITLE
Add Websauna project to Powered by Pyramid

### ISSUE THREAD

**Issue by ericof** [Pylons/trypyramid.com#252]
Add your business, organization, project, or website to the Powered by Pyramid page on trypyramid.com by providing the following information:

entity name: Websauna
entity category:
- [x]  free and libre open source project or application

description: A full stack Python framework for building consumer and business web applications
maintainers: Mikko Ohtamaa (@miohtama) Érico Andrei (@ericof)
logo (will be resized to 700x200 pixels (HxW): https://websauna.org/theme/images/logo-768.png
project URL: https://websauna.org
pypi URL: https://pypi.org/project/websauna/
version control URL: https://github.com/websauna

**Comment by stevepiercy** [comment]
Done in 0d0ab72!
https://trypyramid.com/community-powered-by-pyramid.html

Thank you!
