### ISSUE TITLE
Add MLBPool2 to Powered by Pyramid

### ISSUE THREAD

**Issue by prcutler** [Pylons/trypyramid.com#254]
entity name: MLBPool2
    entity category (choose one):
        free and libre open source project or application
    description: MLBPool2 is a fantasy baseball like application.  Instead of making daily lineups, players choose individual statistical leaders and team standings before the season starts.  Then they watch how their picks perform over the course of the baseball season.
    maintainers: Paul Cutler (@prcutler)
    logo (will be resized to 700x200 pixels (HxW): N/A
    project URL: https://github.com/prcutler/mlbpool2
    demo URL:  https://mlbpool2.com
    version control URL: https://github.com/prcutler/mlbpool2
    docs: https://mlbpool2.readthedocs.io/en/latest/

Thanks for your consideration!

Paul

**Comment by stevepiercy** [comment]
Added! Thank you!
