### ISSUE TITLE
Unable to run "npm run dist"

### ISSUE THREAD

**Issue by invisibleroads** [Pylons/trypyramid.com#258]
This is not urgent, but I noted the following errors yesterday.

1. `npm install` results in 3 vulnerabilities.
```
# Run npm install --save-dev webpack-dev-server@3.1.14 to resolve 2 vulnerabilities
# Run npm install --save-dev url-loader@1.1.2 to resolve 1 vulnerability
```
2. `npm run dist` results in two errors.
```
ERROR in ./src/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./img/pyramid-aliens1-680x425.jpg in ~/Documents/trypyramid.com/src
 @ ./src/main.js 45:0-44

ERROR in ./src/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./img/pyramid-aliens2-680x425.jpg in ~/Documents/trypyramid.com/src
 @ ./src/main.js 51:0-44
```
Both of those files exist, so I am assuming the problem might be somewhere else (and not related to the error message).

**Comment by stevepiercy** [comment]
1. Please submit a PR to resolve these vulnerabilities. I'll merge it.
2. I verified that they're in the repo. I assumed you did a recent pull from master. I just ran `npm run dist` without any issue. The `Module not found` message might be a clue, but that's not a lot to go on.

**Comment by bertjwregeer** [comment]
We've upgraded the whole process. This should no longer be an issue.
