### ISSUE TITLE
Add pyramid-resource to "Extending Pyramid"

### ISSUE THREAD

**Issue by luhn** [Pylons/trypyramid.com#260]
* project name:  pyramid-resource
* project URL:  https://pypi.org/project/pyramid-resource/
* description:  A simple base resource class for URL traversal in Pyramid.
* maintainers:  luhn
* PyPI URL:  https://pypi.org/project/pyramid-resource/
* VCS URL:  https://github.com/luhn/pyramid-resource
* docs URL:  https://pypi.org/project/pyramid-resource/
* demo URL:  N/A
* support (select one):  Community
* addon:  yes
* categories:  routing
* tags:  traversal, resource

**Comment by stevepiercy** [comment]
Closed by af004f896fdaf7bb7424de84a3baf005990f1d47. Thank you!
