### ISSUE TITLE
Add "Office national des forêts" website

### ISSUE THREAD

**Issue by tflorac** [Pylons/trypyramid.com#261]
* entity name: Office national des forêts
* entity category (choose one):  
  * [ ]  company
  * [x]  organization
  * [ ]  free and libre open source project or application
  * [ ]  website
* description: Producing wood, preserving the environment and welcoming the public are the three main assignments of the french national forestry office (Office national des forêts); distributed all over the country, it's 9000 agents are dedicated to these missions.
* maintainers: Thierry Florac (https://github.com/tflorac)
* logo (will be resized to 700x200 pixels (HxW): http://www.pariscotejardin.fr/wp-content/2013/05/LOGO-ONF-Quadri-big.jpg

**Comment by stevepiercy** [comment]
URL for logo is a 404. Please update with a valid URL or upload the logo here.

**Comment by tflorac** [comment]
Hi Steve,
Sorry, link was OK for me!
This is the logo...

![logo-onf-quadri-big](https://user-images.githubusercontent.com/326159/53151080-85fe5800-35b2-11e9-9032-bff3203d3d2b.jpg)

**Comment by stevepiercy** [comment]
Added in 02a6cfb47538cc485016f6b07a0c33bd0b6c437b and d669524bb6873ea8c2ef0f02a3d7d11b146dc79e
