### ISSUE TITLE
Add "Ulthar.net" website

### ISSUE THREAD

**Issue by tflorac** [Pylons/trypyramid.com#262]
* entity name: Ulthar.net
* entity category (choose one):  
  * [ ]   company
  * [ ]   organization
  * [ ]   free and libre open source project or application
  * [x]   website
* description: Ulthar.net is a french website dedicated to the american writer Howard Phillips Lovecraft and the Cthulhu mythos
* maintainers: Thierry Florac (https://github.com/tflorac)
* logo (will be resized to 700x200 pixels (HxW): https://www.ulthar.net/++header++/++settings++PyAMS%20simple%20header/++attr++logo

**Comment by stevepiercy** [comment]
Added in 02a6cfb47538cc485016f6b07a0c33bd0b6c437b and d669524bb6873ea8c2ef0f02a3d7d11b146dc79e
