### ISSUE TITLE
Powered by Pyramid, company Klein & Partner KG

### ISSUE THREAD

**Issue by jensens** [Pylons/trypyramid.com#264]
Please update:

entity name: Klein & Partner KG
entity category (choose one): company
description: Python based web-applications and CMS
logo (will be resized to 700x200 pixels (HxW): https://kleinundpartner.at/@@site-logo/kup-logo.svg
project URL: https://kleinundpartner.at

**Comment by stevepiercy** [comment]
Added in b77e3e5. Thank you!
