### ISSUE TITLE
Powered by Pyramid, Company: gocept

### ISSUE THREAD

**Issue by dhavlik** [Pylons/trypyramid.com#265]
* entity name: gocept gmbh & co. kg
* entity category (choose one):
  * [ X ]  company
  * [ ]  organization
  * [ ]  free and libre open source project or application
  * [ ]  website
* description: Software development with Python, Zope and Pyramid.
* maintainers:
* logo (will be resized to 700x200 pixels (HxW): https://i.imgur.com/OotFL6u.png
* project URL: https://gocept.com
* demo URL:
* pypi URL:
* version control URL:

**Comment by stevepiercy** [comment]
Added in 8b58da5. Thank you!
