### ISSUE TITLE
jQuery 3.5.0 breaks Bootstrap Collapse

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/trypyramid.com#275]
Until this fix here: https://github.com/jquery/jquery/issues/4665 is released, don't upgrade!

**Comment by stevepiercy** [comment]
It looks like it snuck in to the build anyway.

- The select menu on is b0rken: https://trypyramid.com/extending-pyramid.html
- View the response for `vendors.*.js`: https://trypyramid.com/vendors.6e28f52a38999b1c227d.js and search for `jQuery JavaScript Library v3.`.
![Google Chrome005](https://user-images.githubusercontent.com/102112/82632916-8bc85c00-9bae-11ea-9849-3d1acb6f01d5.png)

**Comment by stevepiercy** [comment]
[3.5.1 was released](https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/). I'll try building it locally without the jQuery pin and see what happens.

**Comment by bertjwregeer** [comment]
Already done, and pushed.

**Comment by stevepiercy** [comment]
you fast! 💨

**Comment by bertjwregeer** [comment]
Bootstrap Collapse doesn't work with jQuery 3.5.1 either. So we need to replace that with something that doesn't require jQuery 2.x

**Comment by stevepiercy** [comment]
meh, downgrade until then?
