### ISSUE TITLE
bootstrap-multiselect is broken with jQuery 3.5.1

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/trypyramid.com#277]
This breaks the extending https://trypyramid.com/extending-pyramid.html filtering. We should find a replacement or something.

**Comment by bertjwregeer** [comment]
@stevepiercy 

I've temporarily hard-pinned jQuery to 3.4.1, which seems to work.

**Comment by stevepiercy** [comment]
Yeah, for now.

Here's a [jsFiddle with the following requirements](https://jsfiddle.net/0qpxd659/3/), and demo HTML and JS copied from https://davidstutz.de/bootstrap-multiselect/#getting-started. It seems to work.

- jQuery 3.5.1
- Bootstrap 3.3.7
- bootstrap-multiselect 0.9.15

**Comment by stevepiercy** [comment]
This combination seems to work locally. We'll see in a minute for the production site.

**Comment by stevepiercy** [comment]
Yup, we're good. Setting both dependencies and resolutions to jQuery 3.5.1 was the ticket. But I expect this will all fall apart when jQuery 4.0.0 is released.

**Comment by bertjwregeer** [comment]
I had tried that before... no joy. Great, glad it's solved!
