### ISSUE TITLE
Add pyramid-dynamodb-sessions to Extending Pyramid

### ISSUE THREAD

**Issue by luhn** [Pylons/trypyramid.com#279]
Name: pyramid-dynamodb-sessions
URL: https://pypi.org/project/pyramid-dynamodb-sessions/
description: DynamoDB-backed sessions
maintainers: luhn
PyPI URL: https://pypi.org/project/pyramid-dynamodb-sessions/
VCS URL: https://github.com/luhn/pyramid-dynamodb-sessions
docs URL: https://pypi.org/project/pyramid-dynamodb-sessions/
demo URL: N/A
support: Community
addon:  Yes
category: sessions
tags: aws, dynamodb, serverless

**Comment by mmerickel** [comment]
@luhn I pushed https://github.com/Pylons/trypyramid.com/pull/280. Can you review?
