### ISSUE TITLE
Notify third parties of new Pyramid logo

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#29]
Send the current Pyramid logo for incorporation into their products and projects. Please add to the list.
- [x] JetBrains/PyCharm
- [x] Plone Conference (cewing)
- [x] https://ziggurat-foundations.readthedocs.io/en/latest/
- [x] https://en.wikipedia.org/wiki/Pylons_project
- [x] https://docs.immun.io/docs/python-with-pyramid

**Comment by stevepiercy** [comment]
Blocked by #120

**Comment by zupo** [comment]
* https://en.wikipedia.org/wiki/Pylons_project
* https://docs.immun.io/docs/python-with-pyramid

**Comment by stevepiercy** [comment]
@zup Added to checklist. Thank you!

**Comment by stevepiercy** [comment]
Blocked by #159

**Comment by stevepiercy** [comment]
All done!
