### ISSUE TITLE
Reduce the size and number of requests

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#3]
The home page currently makes 13 requests for 1.3MB of data. That's too much.

**Comment by blaflamme** [comment]
@stevepiercy sure we'll have to srtipdown somehow, but the real thing to test is in the dist directory. Now you're looking a the devmod, do run `$ npm run dist` and then open up the index.html file, this is what would be deployed. Make sure to not commit the dist directory until it's deployable, I'll take care of that once optimized.

In the end what we could do is to only include the parts we're using from bootstrap and the highlighter.

**Comment by stevepiercy** [comment]
OK. I see now. It's down to 8 requests and 363Kb in dist. Agree on including only those parts we need from Bootstrap and Highlighter.js. Bootstrap is pretty easy, but I'm not familiar with Highlighter's process.

There is a [build tool for Highlighter.js](http://highlightjs.readthedocs.org/en/latest/building-testing.html#building) which might need to be run manually or could be included in the build process. It looks like it is not included in the npm package and would need to be pulled from the repo.

**Comment by pauleveritt** [comment]
> On Apr 15, 2015, at 3:54 PM, Steve Piercy <notifications@github.com> wrote:
> 
> OK. I see now. It's down to 8 requests and 363Kb in dist. Agree on including only those parts we need from Bootstrap and Highlighter.js. Bootstrap is pretty easy, but I'm not familiar with Highlighter's process.
> 
> There is a build tool for Highlighter.js <http://highlightjs.readthedocs.org/en/latest/building-testing.html#building> which might need to be run manually or could be included in the build process. It looks like it is not included in the npm package and would need to be pulled from the repo.
> 
pylonsproject.org makes (according to Chrome) 65 requests. I think we can make optimization into some tasks for a post-launch milestone.

—Paul

**Comment by blaflamme** [comment]
@pauleveritt since pylonsproject.org will be refactored somehow after trypyramid.com I wouldn't put too much effort on improving it. It still works in its actual form.

**Comment by pauleveritt** [comment]
Actually that is my point as well. I used pylonsproject.org to reflect that we can live with a bunch of requests. Most important thing is to get something out the door.

—Paul

**Comment by blaflamme** [comment]
@pauleveritt sorry, misread you :(

Totally agree with you.

**Comment by bertjwregeer** [comment]
Currently it loads ~17 assets, with ~1.53 MB of data transfer. It's fine.
