### ISSUE TITLE
google groups embedding deprecated

### ISSUE THREAD

**Issue by slav0nic** [Pylons/trypyramid.com#316]
https://trypyramid.com/community-feeds.html

![deprecation](https://user-images.githubusercontent.com/199555/146643449-5021f031-00b3-421f-a6e5-ca62c87c538b.png)

**Comment by stevepiercy** [comment]
Thank you! Confirmed. In Incognito mode:
![Screen Shot 2021-12-18 at 10 15 11 PM](https://user-images.githubusercontent.com/102112/146665924-34a19cc8-6848-4839-aea5-b0815443f357.png)

**Comment by stevepiercy** [comment]
Google Groups suggests the new way forward is to only provide a link to the group. That will mess up the layout. To fix this issue, I would like to do the following:

1. Reorder the text of the feeds, sorted by greatest number of participants:
    > Subscribe to the Google Group, pylons-discuss. Follow us on Twitter @PylonsProject. Chat with us in #pyramid on IRC.
2. Put Google Group `div` first, into its own row. Retain the `h3` heading. Add a `p` and insert the text from the introduction:
    `<p>Visit <a href="https://groups.google.com/forum/#!forum/pylons-discuss">pylons-discuss</a></p>`
3. Put Twitter second, into its own row.
4. Leave IRC as is.

**Comment by stevepiercy** [comment]
@slav0nic if you would like to submit a PR to fix this, I would greatly appreciate it! Thank you!

**Comment by stevepiercy** [comment]
Closed by #317.
