### ISSUE TITLE
Grant access to public trypyramid.com to few members

### ISSUE THREAD

**Issue by goodwillcoding** [Pylons/trypyramid.com#34]
@blaflamme can I and @stevepiercy have access to publish trypyramid.com

pretty please

**Comment by stevepiercy** [comment]
See also https://github.com/Pylons/tpc/issues/21#issuecomment-152168763

**Comment by goodwillcoding** [comment]
@blaflamme ... alternatively if you hosting the site is something you want to be free of, let me know I will take it over.

**Comment by goodwillcoding** [comment]
from IRC discussion:

@blaflamme will move trypyramid.com to a different VPS after NY holidays.
@goodwillcoding will follow up with @blaflamme on Jan 12 to see where we are at

/cc: @stevepiercy

**Comment by stevepiercy** [comment]
Fallback position: @stevepiercy will build a staging site for the project (possibly trypyramid.stevepiercy.com) so folks can see and be better informed of the progress to date.

**Comment by blaflamme** [comment]
@goodwillcoding @stevepiercy best would be to merge finished PR in a dev branch that could be publishable under dev.trypyramid.com so we can see the work in progress before merged to master and deployed to prod

**Comment by mmerickel** [comment]
We need to consider using github pages for these sites. They are static and it's silly how hard they are to deploy right now. It should be as simple as merging things into master. I'm happy to do the work but someone would need to set the DNS records as I don't have access to them.

**Comment by blaflamme** [comment]
@mmerickel I'm almost done with the setup and it would be as easy as to push to another remote

**Comment by mmerickel** [comment]
I've taken this discussion to the mailing list. It's become very important to me that we fix the hosting situation of these sites if we want to support easier contributions.

**Comment by blaflamme** [comment]
@mmerickel Sure, that would be as simple as people submitting PR, we review and merge as they fulfill the requirements, and then people who has publish access could push to remote prod. So it'll be a similar process than what we do when releasing pyramid and publish to pypi.

**Comment by mmerickel** [comment]
Let's talk about it on the mailing list. I'm really concerned about the bus factor on these sites right now more than even ease of updating. They are static sites but for some reason only like 1 or 2 people have access to them (0 in the case of webob.org). I need a real reason why we aren't considering github pages behind a CNAME for this. These sites should be as darn simple as possible for github.com/Pylons team members to configure.

**Comment by pauleveritt** [comment]
@mmerickel has a good point. We’ve put too much on the shoulders of Blaise, which isn’t fair to him. Having something that is as normal as possible, with a workflow that’s documented by other people, seems sane.

**Comment by goodwillcoding** [comment]
@blaflamme can weigh in, but I've offered to take it over. I am sure we can come up with some structure that avoids buses. I think the site is static now. I am guessing it can be published to github

**Comment by blaflamme** [comment]
@stevepiercy @mmerickel @goodwillcoding @pauleveritt 

trypyramid.com is now serving from the new setup and can be deployed using a git push. I'll finalize people access later today. Here's the basic instruction set to release and deploy a new version:

https://github.com/Pylons/trypyramid.com/blob/master/RELEASE.md

What I propose is to work on feature branches and then merge to dev until we reach a new release to prevent pushing master to production and break things up. That would also help us validating what we're going to publish.

**Comment by stevepiercy** [comment]
w00t! A Pyramid 1.6 release *and* this?! Somebody pinch me! :smile:

**Comment by blaflamme** [comment]
In fact, since we need to run dist to have a deployable project we can merge PR to master without running into problems, then  run dist and do the release process before deploying.

**Comment by blaflamme** [comment]
@stevepiercy and @goodwillcoding have provided their public ssh keys to get access to deployment, if @mmerickel or @pauleveritt need to have access just send me your public ssh keys.

**Comment by pauleveritt** [comment]
If this is triggered on git push, then I’m covered.

THANKS BLAISE !!!

—Paul

**Comment by blaflamme** [comment]
Setup is done, people have access and trypyramid.com is live. Closing this ticket.
