### ISSUE TITLE
Add contributing.md to document how to contribute

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#35]
We cannot assume that contributors know our process for accepting and publishing contributions when it's not documented.

GitHub uses contributing.md:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

Example from another Pylons Project:
https://github.com/Pylons/pyramid/blob/master/contributing.md

**Comment by blaflamme** [comment]
https://github.com/Pylons/trypyramid.com/commit/9a9d0425a12a83b83ef35ee0af1d6b80ce013246
