### ISSUE TITLE
Expanding code samples on the home page not working

### ISSUE THREAD

**Issue by krysros** [Pylons/trypyramid.com#353]
The code samples on the home page are expanded by default and expanding/shrinking doesn't work when you click the arrow.

**Comment by slinkp** [comment]
Confirmed in both Firefox 117.0.1 (MacOS) and Chrome 116.0.5845.187 (MacOS).
Also, you can't visually distinguish where one sample ends and one begins.
![Screenshot 2023-09-15 at 9 11 19 AM](https://github.com/Pylons/trypyramid.com/assets/98610/d1b11997-2d2e-4b1e-996f-44d71b70772c)

**Comment by slav0nic** [comment]
This is why https://github.com/highlightjs/highlight.js/wiki/security
highlight.js > 11 stipes html inside code block, so all spans `.code-top`, `.code-bottom`  not present
