### ISSUE TITLE
Potential new button for "powered by"

### ISSUE THREAD

**Issue by Jeremydavisvt** [Pylons/trypyramid.com#37]
Font is Open Sans (just like the site) Tried uploading the .psd in a zip but github kept yelling at me. 

![trypyramid](https://cloud.githubusercontent.com/assets/2834149/12087128/7ee01a6c-b29e-11e5-901f-b8c96f11a90a.png)

White version 

![trypyramidwhite](https://cloud.githubusercontent.com/assets/2834149/12087636/943cf2fa-b2a2-11e5-873b-91b49a61f467.png)

Not sure on text color for either options

**Comment by blaflamme** [comment]
@Jeremydavisvt thanks for the proposal. I'll take a closer look but offhand it would be better to propose them in three colors (red, black and white) on transparent background. That way you may cover most contexts. Also the typo is too big against the logo, and I would probably go with Pyramid Powered, with the powered below.

**Comment by Jeremydavisvt** [comment]
+1 on transparent background. I'm not so sure on the "Pyramid Powered" thing though. badges like this usually say, "Powered by x", "Made with x" or "an x project". 'Pyramid Powered' just sounds off.

**Comment by blaflamme** [comment]
Ideally according to proportions it would looks like

![pyramidpowered](https://cloud.githubusercontent.com/assets/454978/12096586/46018b4a-b2e4-11e5-9d98-ba107e6c5075.png)

**Comment by Jeremydavisvt** [comment]
These look _way_ better. just needs transparent backgrounds.

**Comment by blaflamme** [comment]
Sure it was just to outline the idea, I'll produce them at different sizes and we should put them, like official logos somewhere on trypyramid.com

**Comment by Jeremydavisvt** [comment]
Cool. makes sense to continue conversation over in #22 (didnt know there was already an issue open when I made this one, as per IRC :P)

**Comment by blaflamme** [comment]
I prefer looking at multiple issues that cover a few points, or just one, than a huge issues covering too much points.

**Comment by Jeremydavisvt** [comment]
If only github supported things like Epics.

**Comment by stevepiercy** [comment]
This issue actually covers two separate issues:

* The page named "Artwork" under "Media" in issue #38 and PR #53.
* The page named "Powered by Pyramid" in issue #22 and PR #46. It might get a "Powered by Pyramid" button or a link to "Artwork" for guidelines of how to add the button to your website.

Closing this issue in favor of those two.
