### ISSUE TITLE
Resources page: purpose of grey background headings

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#48]
On [Resources](https://trypyramid.com/resources.html) there is an area with a grey background whose purpose is not clear. It seems that they are supposed to be column headings, but the items beneath them don't fall under the description of the column headings.

Is the grey bar present to break up the visual monotony of the white background?

**Comment by blaflamme** [comment]
@stevepiercy this is a simple way to express a content block, then each content block doesn't need to relate visually or aligned with the others. They have to make sense on their own and provide self-contained layout and organization for their own purpose. The home page does that.

**Comment by stevepiercy** [comment]
On Resources, the content in the grey bar is redundant. Would it be all right to remove the grey bar and its content?

**Comment by blaflamme** [comment]
Possible... or find a way to make the information better organized, I haven't figured that out yet. What I fear in the short term is that we get all the info as dumb listing like the addons page. It's very hard to make sense out of that, and then by extent we'll have this for the long term :(

**Comment by stevepiercy** [comment]
OK, let's just let this issue stew for a while until it's done. There are more important issues yet.

**Comment by stevepiercy** [comment]
Resolved in 5baae49
