### ISSUE TITLE
Add Site Map

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#50]
See the proposed sitemap: https://github.com/Pylons/trypyramid.com/wiki/Site-Map-of-trypyramid.com

**Comment by zupo** [comment]
https://www.npmjs.com/package/sitemap-webpack-plugin?

**Comment by stevepiercy** [comment]
It would be nice to declare our URLs in one place, and populate the sitemap, navigation bar, and possible future features. sitemap-webpack-plugin has the right idea. Maybe we can steal some ideas from its compatible [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin/)?

I never liked the URL structure we have now. I just hacked it together where all URLs are in a single root directory because I didn't know any better method with webpack.

**Comment by bertjwregeer** [comment]
Hugo gave this to us for free:

https://trypyramid.com/sitemap.xml

**Comment by stevepiercy** [comment]
Submitted to Google, too.

**Comment by stevepiercy** [comment]
It needs fully qualified URLs, not just the filepath.

**Comment by bertjwregeer** [comment]
We explicitly don't add the full qualified URL to our build process because of this. Shakes fist at Google.

Meh, all pages are linked, it'll index them all.

**Comment by stevepiercy** [comment]
It's not Google. It's a spec. https://www.sitemaps.org/protocol.html#locdef

**Comment by bertjwregeer** [comment]
Welp... shakes fist at Sitemaps

**Comment by mmerickel** [comment]
We can change the baseurl at build time if we want.

**Comment by stevepiercy** [comment]
[Something like adding an env var](https://github.com/Pylons/trypyramid.com/blob/master/.github/workflows/build.yaml#L24)?

```
env:
  baseurl: "https://trypyramid.com"
```

**Comment by mmerickel** [comment]
I think it would be HUGO_BASEURL, but yes we should be able to set that in the build workflow.

**Comment by mmerickel** [comment]
this is fixed now
