### ISSUE TITLE
Create staging environment

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#69]
We need a staging environment so that we can make it easier to review changes and collect feedback. Iterative process FTW!

**Comment by blaflamme** [comment]
yes that'll help showcasing to others

**Comment by cguardia** [comment]
It isn't a high traffic site. Deploy the site to another directory on same host and add a dns record pointing to that?

**Comment by blaflamme** [comment]
@cguardia the idea is to add a host like dev.trypyramid.com that point to another directory and publish there the dev branch of the project, using the same pattern than for prod.

**Comment by zupo** [comment]
I've used Travis to deploy to staging (and production) for a number of years now. Should not be too hard to set up a deploy to staging on every push to master.

How security sensitive is the server running trypyramid.com? Can we allow Travis to SSH into it or rather not?

**Comment by blaflamme** [comment]
We have a pylons account we can add ssh keys to, then files are pushed to a bare repos that are copied over a location that exposes the dist directory.

Like for the other ticket, my concern here is to have to maintain the prod server with all the tooling to output the assets for deployment, I prefer not. Then someone can just commit anything without testing locally if it compiles and render and then get deployed and have the site broke.

**Comment by zupo** [comment]
The way I would do it is to build on Travis. And if the build succeeds only then deploy to server.

And for the first few months, definitely deploy only to staging. Also, disallow (github supports it as of late) direct pushes into master, so everything needs to go via a PR.

**Comment by blaflamme** [comment]
@zupo Sounds better to me. But I never managed to have the tooling installed to travis. Can you take this part in charge?

**Comment by zupo** [comment]
Mhm, will take a jab at it.

**Comment by mmerickel** [comment]
I think it'd be better to just have travis emit a webhook back to the server when a build was complete. The server then could have scripts that would pull the asset and put it in the right folder and then reload nginx.

I think in a perfect world we could do this with a wildcard domain and have the server host a different subdomain for each pull request. Something like `pr-69.staging.trypyramid.com`. Or even just put it all under `pylonsproject.org` for staging purposes, instead of a different wildcard for each site. Then it'd be `pr-69-trypyramid.staging.pylonsproject.org` versus `pr-69.staging.pylonsproject.org`. Does this sound crazy? It seems fairly straightforward to setup if we can handle the webhook.

1) Get travis to build the assets.
2) Get travis to save the assets.
3) Get travis to emit a webhook to pylonsproject.org.
4) A cheap-o listener on pylonsproject.org which can download the asset, copy them to the correct subfolder and reload nginx.
5) Configure nginx to host various folders at subdomains.

The cheap-o webhook is nice because if something fails we can just ping it again.

**Comment by bertjwregeer** [comment]
Wouldn't even need to restart NGINX...

**Comment by zupo** [comment]
Exactly what you describe can be had on Heroku, supported out-of-the-box. Possibly for free. With a few clicks you configure Heroku to build and deploy an app every time a PR is made and put the URL to the app into the PR so it's right there when you need it.

Shall I set it up? I'm gonna need admin permissions on this repo or a Skype/Hangouts session with someone who is an admin so drive them through the process.

**Comment by blaflamme** [comment]
can dokku do that?

**Comment by stevepiercy** [comment]
@zupo [per conversation in IRC today](https://botbot.me/freenode/pyramid/2017-03-20/?msg=82721210&page=3) we discussed how to automate deployment. We're going for deployment straight to production, and discarding a staging server idea at this time:

push -> guthub -> travis -> deploy

1. What specifically needs to be set up on GitHub?
2. Are there other set up pieces for the production server?

I have Admin access to this repo and pylonsproject.org, so I can at least do the GitHub pieces. @blaflamme would need to do the production server pieces, if any.

**Comment by zupo** [comment]
@stevepiercy: login to travis-ci.org, go to Pylons org, toggle trypyramid.com repo. Then add .travis.yml to repo and push. The build should run. 

As for what to put in .travis.yml: you want to run some tests, if there are no unit tests, then just build the thing so at least the build process is covered by Travis. Then you need to add a "deploy" step to .travis.yml to push generated files to production server. These are the supported deploy methods: https://docs.travis-ci.com/user/deployment

**Comment by stevepiercy** [comment]
Thanks @zupo!

I enabled Travis for this repo and pylonsproject.org, and to "Build only if .travis.yml is present".

I'll have to think about what tests, if any, we want to run. I guess if the site builds, then that's good enough. I'm open to suggestions.

Linode is not one of the providers, but it looks like we can deploy with Git and SSH keys:
https://docs.travis-ci.com/user/deployment/custom/#Git

Or Travis on successful build could fire something (I don't know what the term is in Travis or if it even exists, so I'd appreciate a reference) that would tell the server to pull from the master branch.

Either way, it looks like we'll need @blaflamme to provide the final piece.

**Comment by bertjwregeer** [comment]
Each PR is now automatically built, and artifacts are attached to the build. To validate download the artifact, and serve it, and you are good to go.

We may be able to add a staging environment in the future.

**Comment by stevepiercy** [comment]
Closing as this is not needed with a static website that is automatically deployed.
