### ISSUE TITLE
Merge Pyramid add-ons and Pyramid development environments into Extending Pyramid

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#76]
@blaflamme I'd like your thoughts on this issue. Do you know of other jQuery plugins that would be better?

Combine these two pages into one.

Pyramid add-ons
https://trypyramid.com/resources-add-ons.html

Pyramid development environments
https://trypyramid.com/resources-development-environments.html

=>
Extending Pyramid
https://trypyramid.com/resources-extending-pyramid.html

Add the jQuery plugin Isotope
http://isotope.metafizzy.co/

Customize the layout, styles, animations.

Work is on the branch [page-extending-pyramid](https://github.com/Pylons/trypyramid.com/tree/page-extending-pyramid).

**Comment by blaflamme** [comment]
@stevepiercy in the current form it would be just worst to have a page with even more content. My first thought on that was to use the «card» approach to list all of the different extension/projects/..., and the plugin you're suggesting shows this, so yes it's in the right direction. I was thinking about the isotope plugin, but any of those plugins can filter based on tags so we could then mixed up anything we like there. Also it would be better to remove the data off the document and use a json file to provide it to the template at compile time or to the plugin at runtime... Easier to maintain.

**Comment by stevepiercy** [comment]
[Isotope](http://isotope.metafizzy.co/) seems to have more flexibility, so unless you have a problem with its GPLv3 license, we can use it.

For JSON implementation, how would that work? I see this:

**webpack.tmpl.config.js**
```js
var data = require(path.resolve(__dirname, 'src/templates/data.json'));
```
**src/templates/data.json**
```json
  "pages": {
    "index.html": {
      "title" : "Home Page",
      "nav_id": "item-1",
      "needsTsNav": true
    },
    "colors.html" : {
      "title" : "Colors",
      "nav_id": "item-2"
    },
    "resources.html" : {
      "title" : "Resources",
      "nav_id": "item-3"
    },
    "resources-development-environments.html" : {
      "title" : "Development Environments",
      "nav_id": "item-4"
    }
```

To implement the data, would I do something like this?

```json
    "resources-extending-pyramid.html" : {
      "title" : "Extending Pyramid",
      "data": {
        "key1": "value",
        "key2": "value",
        ...
        "keyN": "value",
      },
      "nav_id": "item-5"
    }
```

...where my json data object would consist of the following keys?
* supported (true or false)
* category
* name
* description
* maintainers
* project_url
* version_control_url
* documentation_url
* pypi_url
* demo_url
* comments

**Comment by blaflamme** [comment]
I don't have any problem with the license in the current project, lets see which one gives us best options and ease of integration I'm still not sure. For data I'm not sure about using the current data flow, I would prefer having that info separated in its own file since it'll get long I fear. Also I would prefer to refactor naming to proper camelCase naming in that context as opposed to underscore python naming, like versionControlUrl, documentationUrl, pypiUrl, ... Your object model looks fine.

**Comment by stevepiercy** [comment]
> use a json file to provide it to the template at compile time or to the plugin at runtime

Let's say I have a JSON data file. How do I get the data into the rendered HTML so that Isotope can filter and sort it? Is this a SWIG thing or something else? I have no idea where to look.

**Comment by stevepiercy** [comment]
I got a very rough integration with webpack going, thanks to this:
http://isotope.metafizzy.co/appendix.html#webpack

**Comment by blaflamme** [comment]
@stevepiercy there are multiple ways of doing this, SWIG is probably not the best way to do that. I'll give a shot on a branch.

**Comment by stevepiercy** [comment]
FWIW, I finally got the Isotope plugin to work, including basic buttons to filter by one category at a time. YAY!

Next I need help deciding how to filter the available data. Here are two UI options that I like:

* checkboxes: http://codepen.io/desandro/pen/JGKyrY
* toggle buttons: http://codepen.io/desandro/pen/zrMXQv

These allow inclusive selection, both within and across attribute types.

I am debating whether to have a single attribute type or at least two:
* Support: Official, Community
* Tag: API, Authentication, ... , WSGI Servers

As far as the JSON data injection, I put all the data into a database, and wrote a script that returns all records and dumps it into an HTML template. This at least gets the data into a tabular format, making it easier to work with to change the layout. Nonetheless, I still don't know how to get a JSON file shoved into a `.pt`.

**Comment by stevepiercy** [comment]
I went with buttons, but using small single, not grouped, Bootstrap buttons.
http://getbootstrap.com/css/#buttons-sizes
http://codepen.io/desandro/pen/zrMXQv

I have decided on these attribute types:

* Support
* Categories (rename of Tag) are categories
* Tags can be arbitrary, e.g., LDAP, JSON, XML-RPC, tomato

I left out some data in my database, which will take me a couple of hours to complete, as there is no pattern to the arrangement and order of elements.

**Comment by stevepiercy** [comment]
Work is on the branch [page-extending-pyramid](https://github.com/Pylons/trypyramid.com/tree/page-extending-pyramid).

**Comment by stevepiercy** [comment]
Moving conversation to the PR #84, and closing this issue.
