### ISSUE TITLE
Change monospace font for code examples

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#78]
The monospace font in the syntax highlighter, Inconsolata, displays ' as ’ and " as ”, which I find irritating. Google Fonts has a bunch of other monospace fonts that don't have that behavior, are legible, and have distinctive character pairs (O and 0, l and I), including Source Code Pro, Roboto Mono, Ubuntu Mono, and Cuisine.

- [x] @blaflamme pick font
- [x] @blaflamme or @stevepiercy implement decision

**Comment by stevepiercy** [comment]
[Source Code Pro](https://www.google.com/fonts/specimen/Source+Code+Pro) is the most legible of the four for me. I'll go with this one.

**Comment by blaflamme** [comment]
@stevepiercy looking at this I would go with ```Cousine```, ```Source Code Pro``` doesn't look great and it doesn't match well with the current site typo. I'm adding it to a template refactor branch I'm working on.

Source Code Pro
![screen shot 2016-05-02 at 11 27 28 am](https://cloud.githubusercontent.com/assets/454978/14958546/40c86162-1059-11e6-9718-2ab3f4529bcf.png)

Roboto Mono
![screen shot 2016-05-02 at 11 27 58 am](https://cloud.githubusercontent.com/assets/454978/14958559/53b882de-1059-11e6-90cb-d70ad86c9613.png)

Droid Sans Mono
![screen shot 2016-05-02 at 11 28 30 am](https://cloud.githubusercontent.com/assets/454978/14958566/5ba5ae90-1059-11e6-945e-730d9d8404f6.png)

Cousine
![screen shot 2016-05-02 at 11 28 57 am](https://cloud.githubusercontent.com/assets/454978/14958574/6158b90e-1059-11e6-8bd6-e68c42b22882.png)

**Comment by blaflamme** [comment]
@stevepiercy my branch is here https://github.com/Pylons/trypyramid.com/tree/ejs-ify

**Comment by blaflamme** [comment]
Done
